//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anketör_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cevap
    {
        public int CevapID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> SoruID { get; set; }
        public Nullable<int> SecenekID { get; set; }
        public Nullable<System.DateTime> CevapTarihi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Secenekler Secenekler { get; set; }
        public virtual Sorular Sorular { get; set; }
    }
}
